openapi: 3.0.2

info:
  title: Example API
  description: This is a sample API for this test
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1

paths:
  /connexion-routed-endpoint:
    get:
      summary: "This endpoint is routed by connexion"
      responses:
        200:
          description: success
